mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
tun:
  enable: false
  stack: system
  auto-route: true
  auto-detect-interface: true
  auto-redirect: false
  strict-route: false
  dns-hijack:
    - any:53
    - tcp://any:53
dns:
  enable: true
  enhanced-mode: fake-ip
  listen: 0.0.0.0:1053
proxies: []
proxy-groups: []
rules: []
